<?php  //[STAMP] f19767b66054f9b6d0ff9f15e6ab5c3a
// phpcs:ignoreFile
namespace App\Tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
