parameters:
    app.rm.api.url: '%env(RM_API_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $url: '%app.rm.api.url%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    sentiment_analysis:
        class: davmixcool\Analyzer

      ## --------------- ##
      ##    Services     ##
      ## --------------- ##

    app.services.review_service:
        class: App\Services\ReviewService
        autowire: true
        public: true
        arguments:
            $reviewRepository: '@App\Repository\ReviewRepository'
            $reviewFactory: '@App\Factory\ReviewFactory'

    app.services.rick_and_morty_service:
        class: App\Services\RickAndMortyService
        autowire: true
        public: true
        arguments:
            $url: '%app.rm.api.url%'



    app.services.app_serializer:
        class: App\Services\AppSerializer
        autowire: true
        public: true

      ## --------------- ##
      ##   Controllers   ##
      ## --------------- ##

    App\Controller\ReviewController:
        class: App\Controller\ReviewController
        autowire: true
        public: true
        arguments:
            $appSerializer: '@app.services.app_serializer'
            $reviewService: '@app.services.review_service'

    App\Controller\EpisodesController:
        class: App\Controller\EpisodesController
        autowire: true
        public: true
        arguments:
            $appSerializer: '@app.services.app_serializer'
            $rickAndMortyService: '@app.services.rick_and_morty_service'
            $reviewService: '@app.services.review_service'
